### ISSUE TITLE
宣言について

### ISSUE THREAD

**Issue by u-Hoshi** [shunsukeeen/password#1]
var,let,constを使われてますが、varは自由が利きすぎるためバグの温床になります。
そのためvarなしで作成してみて下さい。
[参考記事](https://qiita.com/taiju_suzuki/items/49ed558bd837452353b8)

**Comment by shunsukeeen** [comment]
@u-Hoshi 
Delete var and replace let, const.
Please check it.

**Comment by u-Hoshi** [comment]
@shunsukeeen 
Sorry I delayed to check.

No problem.

[![LGTM](https://lgtm.page.link/gnrinjNzJK7Ebf1j7)](https://media4.giphy.com/media/l4HnKwxpPDoPmL9bG/200w.gif)
